open.png = function(name, width=3.05, height=2.8, units='in', resolution=300, points=9, xmin=0.15,xmax=0.99,ymin=0.17,ymax=0.99,plt=c(xmin,xmax,ymin,ymax), mgp=c(2.2,1,0), pch=".", ...) {
 png(name, width=width, height=height, pointsize=points, units=units, res=resolution)
 par(plt=plt, mgp=mgp, pch=pch, ...)
}
shading = c("#41AA41", "#82E682") #c("#89BAF5", "#DEEBFA")

open.png('bayes_poissoneg_likelihood.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
par(yaxs='i')
xx = 0:15
plot(xx, dpois(xx, 0.5), col=2, pch=1, ylim=c(0,0.65), xlab='N', ylab=expression(P(N*group("|",mu,""))))
points(xx, dpois(xx, 2), col='forestgreen', pch=2)
points(xx, dpois(xx, 7), col=4, pch=3)
legend('topright', c(expression(mu==0.5), expression(mu==2), expression(mu==7)), inset=0.02, col=c(2,'forestgreen',4), pch=1:3)
dev.off()

open.png('bayes_poissoneg_prior.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
par(xaxs='i', yaxs='i')
curve(0*x+1, col=2, xlim=c(0,50), ylim=c(0,2), xlab=expression(mu), ylab=expression(P(mu)), axes=F)
axis(1, at=c(0,50), lab=c(0, expression(infinity)))
axis(2, at=1, lab=expression(epsilon))
box()
dev.off()





xx = seq(0.5, 3, len=1000)
f = function(x) dnorm(x, 2, 0.19) + 0.13*dnorm(x, 1.65, 0.05) + 0.2*dnorm(x, 1.5, 0.4)
ff = f(xx)
ff = ff / sum(ff) / (xx[2]-xx[1])
getdist.1d(list(mids=xx, counts=ff, density=ff))
probs = c(0.9705845, 0.1190615)

open.png('bayes_ci_maxp.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
par(yaxs='i')
plot(1, 1, type='n', xlim=c(0.5,3), ylim=c(0,1.8), xlab=expression(theta), ylab=expression(P(group("",theta,"|")*data)), axes=F)
abline(h=probs, lty=2, col='gray50')
j = which(ff >= probs[2])
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[2], border=NA)
j = which(ff >= probs[1] & xx < 1.75)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
j = which(ff >= probs[1] & xx > 1.75)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
points(xx, ff, type='l')
points(xx[which.max(ff)], max(ff), col=4, pch=19)
abline(h=probs, lty=2, col='gray50')
legend('topright', c('68.3%', '95.4%'), inset=0.02, pch=15, col=shading)
axis(1)
axis(2)
box()
dev.off()

open.png('bayes_ci_mean.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
m = weighted.mean(xx, ff)
par(yaxs='i')
plot(1, 1, type='n', xlim=c(0.5,3), ylim=c(0,1.8), xlab=expression(theta), ylab=expression(P(group("",theta,"|")*data)), axes=F)
j = which.min(abs(xx-m))
while (sum(ff[j])/sum(ff) < pchisq(4,1)) j = c(j[1]-1, j, max(j)+1)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[2], border=NA)
j = which.min(abs(xx-m))
while (sum(ff[j])/sum(ff) < pchisq(1,1)) j = c(j[1]-1, j, max(j)+1)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
points(xx, ff, type='l')
j = which.min(abs(xx-m))
points(xx[j], ff[j], col=4, pch=19)
legend('topright', c('68.3%', '95.4%'), inset=0.02, pch=15, col=shading)
axis(1)
axis(2)
box()
dev.off()

open.png('bayes_ci_perc.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
zquantile = function(x, p, q) {j = 1; while (sum(p[1:j])/sum(p)<q) j=j+1; j}
par(yaxs='i')
plot(1, 1, type='n', xlim=c(0.5,3), ylim=c(0,1.8), xlab=expression(theta), ylab=expression(P(group("",theta,"|")*data)), axes=F)
j = zquantile(1:length(ff), ff, 0.023):zquantile(1:length(ff), ff, 0.977)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[2], border=NA)
j = zquantile(1:length(ff), ff, 0.1585):zquantile(1:length(ff), ff, 0.8415)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
points(xx, ff, type='l')
j = zquantile(1:length(ff), ff, 0.5)
points(xx[j], ff[j], col=4, pch=19)
legend('topright', c('68.3%', '95.4%'), inset=0.02, pch=15, col=shading)
axis(1)
axis(2)
box()
dev.off()





xx = seq(0, 2, len=1000)
f = function(x) dnorm(x, -0.25, 0.5)
ff = f(xx)
ff = ff / sum(ff) / (xx[2]-xx[1])
probs = getdist.1d(list(mids=xx, counts=ff, density=ff))$CI$density

open.png('bayes_ci_limit_maxp.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
par(xaxs='i', yaxs='i')
plot(1, 1, type='n', xlim=c(0, 2.1), ylim=c(0,2.499), xlab=expression(theta), ylab=expression(P(group("",theta,"|")*data)), axes=F)
abline(h=probs, lty=2, col='gray50')
j = which(ff >= probs[2])
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[2], border=NA)
j = which(ff >= probs[1] & xx < 1.75)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
j = which(ff >= probs[1] & xx > 1.75)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
points(xx, ff, type='l')
points(xx[which.max(ff)], max(ff), col=4, pch=19)
abline(h=probs, lty=2, col='gray50')
legend('topright', c('68.3%', '95.4%'), inset=0.02, pch=15, col=shading)
axis(1)
axis(2)
box()
dev.off()

open.png('bayes_ci_limit_perc.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
par(xaxs='i', yaxs='i')
zquantile = function(x, p, q) {j = 1; while (sum(p[1:j])/sum(p)<q) j=j+1; j}
plot(1, 1, type='n', xlim=c(0,2.1), ylim=c(0,2.499), xlab=expression(theta), ylab=expression(P(group("",theta,"|")*data)), axes=F)
j = zquantile(1:length(ff), ff, 0.023):zquantile(1:length(ff), ff, 0.977)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[2], border=NA)
j = zquantile(1:length(ff), ff, 0.1585):zquantile(1:length(ff), ff, 0.8415)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
points(xx, ff, type='l')
j = zquantile(1:length(ff), ff, 0.5)
points(xx[j], ff[j], col=4, pch=19)
legend('topright', c('68.3%', '95.4%'), inset=0.02, pch=15, col=shading)
axis(1)
axis(2)
box()
dev.off()

open.png('bayes_ci_limit_mean.png', resolution=200, height=2.5, xmin=0.175, ymin=0.19, xmax=0.98)
par(xaxs='i', yaxs='i')
m = weighted.mean(xx, ff)
plot(1, 1, type='n', xlim=c(0,2.1), ylim=c(0,2.499), xlab=expression(theta), ylab=expression(P(group("",theta,"|")*data)), axes=F)
##j = which.min(abs(xx-m))
##while (sum(ff[j])/sum(ff) < pchisq(4,1)) j = c(j[1]-1, j, max(j)+1)
##polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[2], border=NA)
j = which.min(abs(xx-m))
while (sum(ff[j])/sum(ff) < pchisq(1,1)) j = c(j[1]-1, j, max(j)+1)
polygon(c(xx[j[1]], xx[j], xx[rev(j)[1]]), c(0, ff[j], 0), col=shading[1], border=NA)
points(xx, ff, type='l')
j = which.min(abs(xx-m))
points(xx[j], ff[j], col=4, pch=19)
legend('topright', c('68.3%', '95.4%???'), inset=0.02, pch=15, col=shading)
axis(1)
axis(2)
box()
dev.off()
